# tabspaces = 4

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C\""
key = "P"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C-"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C%"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C|"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001Cc"
key = "T"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001CC"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001CS"
key = "N"
mods = "Control"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"

[keyboard.bindings.command]
args = ["msg", "create-window", "-e", "/bin/zsh", "--login", "--command", "tmux-sessions --all"]
program = "/usr/bin/alacritty"

[[keyboard.bindings]]
chars = "\u001Cx"
key = "W"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C&"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001Cd"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C[/"
key = "F"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C[?"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C:"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001CI"
key = "I"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001CR"
key = "R"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Cz"
key = "Z"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C "
key = "Z"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C,"
key = "Comma"
mods = "Control"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Ch"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Cj"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Ck"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Cl"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001CH"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001CJ"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001CK"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001CL"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001CH"
key = "Left"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001CJ"
key = "Down"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001CK"
key = "Up"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001CL"
key = "Right"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C^"
key = "B"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Cp"
key = "LBracket"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Cn"
key = "RBracket"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C1"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C2"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C3"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C4"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C5"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C6"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C7"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C8"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C9"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C\u001B1"
key = "Key1"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B2"
key = "Key2"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B3"
key = "Key3"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B4"
key = "Key4"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B5"
key = "Key5"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B6"
key = "Key6"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B7"
key = "Key7"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B8"
key = "Key8"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001C\u001B9"
key = "Key9"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Back"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001B`"
# key = "Grave"
# mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B-"
key = "Minus"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B="
key = "Equals"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B]"
key = "RBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "Backslash"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B;"
key = "Semicolon"
mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001B'"
# key = "Apostrophe"
# mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B,"
key = "Comma"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B/"
key = "Slash"
mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001B~"
# key = "Grave"
# mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B!"
key = "Key1"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B@"
key = "Key2"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B#"
key = "Key3"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B$"
key = "Key4"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B%"
key = "Key5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B^"
key = "Key6"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B&"
key = "Key7"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B*"
key = "Key8"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B("
key = "Key9"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B)"
key = "Key0"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B_"
key = "Minus"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B+"
key = "Equals"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B{"
key = "LBracket"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B}"
key = "RBracket"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B|"
key = "Backslash"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B:"
key = "Semicolon"
mods = "Alt|Shift"

# [[keyboard.bindings]]
# chars = "\u001B\""
# key = "Apostrophe"
# mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B<"
key = "Comma"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B>"
key = "Period"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B?"
key = "Slash"
mods = "Alt|Shift"

[shell]
args = ["--login", "-c", "tmux new-session -A -D -s main"]
program = "/bin/zsh"
[window]
decorations = "buttonless"
opacity = 0.95

[window.dimensions]
columns = 110
lines = 33

[window.padding]
x = 0
y = 0
# [window]
# decorations = "none"
# startup_mode = "Fullscreen"
